name: Run External Python Action

on:
  push:
    branches:
      - master

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run external Python action
        uses: carlozanella/deploy-coolify@v0.2
        with:
          input1: "Hello"
          input2: "World"
