name: Run External Python Action

on:
  push:
    branches:
      - master

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run external Python action
        uses: carlozanella/deploy-coolify@v0
        with:
          endpoint: ${{secrets.COOLIFY_ENDPOINT}}
          token: ${{secrets.COOLIFY_TOKEN}}
          app_uuid: dk0owkg8088okckgo8s0ggog
          image_name: nginx
          image_tag: latest

